```yml
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: cls
rendezvousIP: 172.25.1.19
AdditionalNTPSources:
- 172.25.1.33
- 172.25.1.34
hosts:
  - hostname: master1.cls.blackbird.com
    role: master
    rootDeviceHints:
      deviceName: "/dev/sda"
    interfaces:
      - name: ens160
        macAddress: "00:0c:29:13:42:1b"
      - name: ens224
        macAddress: "00:0c:29:13:42:25"
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            address:
              - ip: 172.25.1.19
                prefix-length: 26
            enabled: true
          link-aggregation:
            mode: active-backup
            options:
              miimon: '140'
            port:
              - ens1f1np1
              - ens1f0np0
      dns-resolver:
        config:
          server:
            - 172.25.1.33
            - 172.25.1.34
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 172.25.1.1
            next-hop-interface: bond0
            table-id: 254 
```