```yml
apiVersion: v1
baseDomain: blackbird.com
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp2
networking:
  clusterNetwork:
    - cidr: 192.168.0.0/16
      hostPrefix: 23
  machineNetwork:
    - cidr: 172.25.1.0/26
  networkType: OVNKubernetes
  serviceNetwork:
    - 10.254.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzRkZGI3MDkyODRlNGE4ZDhhNzEzNzU5MjkyZjU3YWY6MklGRFIxTjZZU1BEMjNVOFVUWjZOREQ2Uk0zQUczVThEMzcyWVhOQzhBU1BBWldZRVg1RzBGVTNONk1aT05XQg==","email":"sanuragi@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzRkZGI3MDkyODRlNGE4ZDhhNzEzNzU5MjkyZjU3YWY6MklGRFIxTjZZU1BEMjNVOFVUWjZOREQ2Uk0zQUczVThEMzcyWVhOQzhBU1BBWldZRVg1RzBGVTNONk1aT05XQg==","email":"sanuragi@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTc2NTgzMmQxLTYyYTUtNDY1Ni05YWQyLWJjODhkNmNkZmY2NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOMkZsTURrM1lUY3hORGswTmpKaE9XSTJOak5oT0RJME16YzFZbVV4WlNKOS5iNVpOM0tNbXpOeU9nNm5HS1F1enVvQ2JZUFJvUU5naVJiVWU2Z2UtbmE5bUZDXzZYOEtOVnBVV2Vvb05Oa25BR0Fzd243QnFxZXFIYnZtamJrSDNfMkVCY21mRzJBSkszWWtfVWlCVEE3TFB0bDY2UkI0WjE1cGdFRlIxdzNLT0J3YnBQWXMtN3lDSVppQnAtUDNER25iMzNFYWFxMV9EbmlOY0hETExQcnFISVlJSnFrNjhXYzdVT0JJQWtDOGJvZWVzakNFaFJ1VXI4Qmw0bVprdXNyb2RXNXg4NWs2RTVWbHpRUGJSMGZZcjQtcXZncFR4dF90S3hUTFFGcVNiUXVqM0tWNDhQYjRxZ0daU2NkM1g4Sk13aEtabWN6enJNNDV5TGVCQlBIeEtpaEtydHNBYTFWTlVFRU9GcjVZT2xQb1RDcUxjUHJrRDVUN0FUR1B6cUg2RXU5RWpOa3hkWDZyUGt6V210NlkxSWNlZEh3QnROSW9Zc1ZnRy1KZXl4ZldUUThVRFdQSU1yMGZvLVlJSEtscnNtZlhzX3JXVVVsSEswa280cHM5T3FIRUMyN3hLV2JTUjFCZGtaLU5Rb3pma3Z4QlktbjFxYnU3czlpUVdndXNVa1YtWWpOTVhXWVpWN1QxUUxkeGpIX1pYdWRoY0psRVZRQzVfZFRuclF4Z25scTZ3dFM4S25JekhZX2VwMXZwSnB4YW12bURwZ2hwR2Y4T2FDOHlQbWU2Q0NvSDViQkNmdjJ5Mm43cDZmVC1kb2lveWVqN3JLMTJJWFB4OV8xVWhGOFdRUEV2YnVQQm9nTEVMZ0lxYjFtTl9zOEd3dk50NHhCb2N5Sm1JMHI4ajJHLUdjMFNDd1dsV1lVTDZta3pjUExvQXk3cjR4TjgyR1otSENXaw==","email":"sanuragi@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTc2NTgzMmQxLTYyYTUtNDY1Ni05YWQyLWJjODhkNmNkZmY2NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOMkZsTURrM1lUY3hORGswTmpKaE9XSTJOak5oT0RJME16YzFZbVV4WlNKOS5iNVpOM0tNbXpOeU9nNm5HS1F1enVvQ2JZUFJvUU5naVJiVWU2Z2UtbmE5bUZDXzZYOEtOVnBVV2Vvb05Oa25BR0Fzd243QnFxZXFIYnZtamJrSDNfMkVCY21mRzJBSkszWWtfVWlCVEE3TFB0bDY2UkI0WjE1cGdFRlIxdzNLT0J3YnBQWXMtN3lDSVppQnAtUDNER25iMzNFYWFxMV9EbmlOY0hETExQcnFISVlJSnFrNjhXYzdVT0JJQWtDOGJvZWVzakNFaFJ1VXI4Qmw0bVprdXNyb2RXNXg4NWs2RTVWbHpRUGJSMGZZcjQtcXZncFR4dF90S3hUTFFGcVNiUXVqM0tWNDhQYjRxZ0daU2NkM1g4Sk13aEtabWN6enJNNDV5TGVCQlBIeEtpaEtydHNBYTFWTlVFRU9GcjVZT2xQb1RDcUxjUHJrRDVUN0FUR1B6cUg2RXU5RWpOa3hkWDZyUGt6V210NlkxSWNlZEh3QnROSW9Zc1ZnRy1KZXl4ZldUUThVRFdQSU1yMGZvLVlJSEtscnNtZlhzX3JXVVVsSEswa280cHM5T3FIRUMyN3hLV2JTUjFCZGtaLU5Rb3pma3Z4QlktbjFxYnU3czlpUVdndXNVa1YtWWpOTVhXWVpWN1QxUUxkeGpIX1pYdWRoY0psRVZRQzVfZFRuclF4Z25scTZ3dFM4S25JekhZX2VwMXZwSnB4YW12bURwZ2hwR2Y4T2FDOHlQbWU2Q0NvSDViQkNmdjJ5Mm43cDZmVC1kb2lveWVqN3JLMTJJWFB4OV8xVWhGOFdRUEV2YnVQQm9nTEVMZ0lxYjFtTl9zOEd3dk50NHhCb2N5Sm1JMHI4ajJHLUdjMFNDd1dsV1lVTDZta3pjUExvQXk3cjR4TjgyR1otSENXaw==","email":"sanuragi@redhat.com"}}}'  # Ensure this is filled
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpP5I9LoycW4ZRMv+ksnUt/OCFHWdKLP5QCDF9KAZHPavCywGsx750+T1qz6gu/GYBwXvZIkgL8uAbm5/wBxjSZPN3Z6YKu7+AIt2zwzkgHz4A8pUomWyM7z7Lii0pcpN2nuAf4BIakJEDh07wQrmTiUowV6kbVKj1wdn6K6btwn9utajyUp2BX5ST9f9FZ5s+WrraNnk/HOSq2WHyB602nI09rTiov3an4dLs9Bnu8Ddf4g3+IjsQZDl0vr/WeacVt6gsPCXf7RLZPuGy/9Vl9Z+y0GXmUSu34ObMGCXQFuRgCOI4nTcbmtVZFK0mB1J6LsvlEGoM32ak6BpytG6m2XPl/cLWLTM2V4SdMli+hTNwqAXdWChLN6u355HP9FmwtLoFvBlWgxamdiwtcXbm/LtDLweCn5uXJFU5199DmjUkpyroVhv5dUyhPw1QpBXtYd5VXreJtGkwc/FlJfM6MT9K9LTioGEXTNDCrDbetGPblTnQA8w55MIjUIEGthc= root@gitlab-enterprise.lab.blackmagiclinux.com'  
additionalTrustBundle: |
imageContentSources:
  - mirrors:
    - registry1.ocp2.blackbird.com:8443/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - registry1.ocp2.blackbird.com:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
```