apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: web
  template: 
    metadata: 
      labels: 
        app: web
    spec: 
      containers: 
        - name: nginx
          image: quay.io/openshiftlabs/simpleservice:0.5.0
          ports: 
          - containerPort: 9876

